/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import DAO.SeanceDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modele.SdzConnection;
import modele.Seance;

/**
 *
 * @author noork
 */
public class ManageCours extends javax.swing.JFrame {

    Connection conne;
/**
     * Creates new form ManageCours
     */
        SeanceDAO se = new SeanceDAO(conne);
    public ManageCours() throws ClassNotFoundException, SQLException {
        this.conne = SdzConnection.getInstance();
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(etat_annule);
        bg.add(etat_valide);
        bg.add(etat_encoursvalid);
        etat_encoursvalid.setSelected(true);
        ButtonGroup heure = new ButtonGroup();
        heure.add(h830);
        heure.add(h1015);
        heure.add(h12);
        heure.add(h1345);
        heure.add(h1530);
        heure.add(h1715);
        heure.add(h1930);
        h830.setSelected(true);
        se.remplissagetableauseance(jTable1, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        semaine_seance = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cours_seance = new javax.swing.JTextField();
        type_cours_seane = new javax.swing.JTextField();
        pro_seance = new javax.swing.JTextField();
        grp_seance = new javax.swing.JTextField();
        salle_seane = new javax.swing.JTextField();
        site_seance = new javax.swing.JTextField();
        salle_capacité = new javax.swing.JTextField();
        h830 = new javax.swing.JRadioButton();
        h1015 = new javax.swing.JRadioButton();
        h12 = new javax.swing.JRadioButton();
        h1345 = new javax.swing.JRadioButton();
        h1530 = new javax.swing.JRadioButton();
        h1715 = new javax.swing.JRadioButton();
        h1930 = new javax.swing.JRadioButton();
        etat_valide = new javax.swing.JRadioButton();
        etat_encoursvalid = new javax.swing.JRadioButton();
        etat_annule = new javax.swing.JRadioButton();
        Ajouter = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        seance_date = new com.toedter.calendar.JDateChooser();
        Editer = new javax.swing.JButton();
        id_seance1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        ValueToResearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(181, 222, 222));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("MISE A JOUR DES SEANCES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1452, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(624, 624, 624)
                    .addComponent(jLabel1)
                    .addContainerGap(624, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jLabel1)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(187, 217, 217));

        jLabel2.setText("ID");

        semaine_seance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semaine_seanceActionPerformed(evt);
            }
        });

        jLabel3.setText("Semaine");

        jLabel4.setText("Date");

        jLabel5.setText("Heure_debut/heure fin");

        jLabel6.setText("Etat:");

        jLabel7.setText("Cours:");

        jLabel8.setText("Type Cours:");

        jLabel9.setText("Enseignant(s):");

        jLabel10.setText("Groupe(s):");

        jLabel11.setText("Capacité:");

        jLabel12.setText("Salle:");

        jLabel13.setText("Site:");

        cours_seance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cours_seanceActionPerformed(evt);
            }
        });

        type_cours_seane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_cours_seaneActionPerformed(evt);
            }
        });

        pro_seance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro_seanceActionPerformed(evt);
            }
        });

        grp_seance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grp_seanceActionPerformed(evt);
            }
        });

        salle_seane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salle_seaneActionPerformed(evt);
            }
        });

        site_seance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                site_seanceActionPerformed(evt);
            }
        });

        salle_capacité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salle_capacitéActionPerformed(evt);
            }
        });
        salle_capacité.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salle_capacitéKeyTyped(evt);
            }
        });

        h830.setText("8h30-10h");

        h1015.setText("10h15-11h45");

        h12.setText("12h-13h30");

        h1345.setText("13h45-15h15");

        h1530.setText("15h30-17h");

        h1715.setText("17h15-18h45");
        h1715.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1715ActionPerformed(evt);
            }
        });

        h1930.setText("19h-20h30");
        h1930.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1930ActionPerformed(evt);
            }
        });

        etat_valide.setText("Validé");
        etat_valide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etat_valideActionPerformed(evt);
            }
        });

        etat_encoursvalid.setText("En cours de validation");
        etat_encoursvalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etat_encoursvalidActionPerformed(evt);
            }
        });

        etat_annule.setText("Annulé");
        etat_annule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etat_annuleActionPerformed(evt);
            }
        });

        Ajouter.setText("Ajouter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        Editer.setText("Editer");
        Editer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditerActionPerformed(evt);
            }
        });

        id_seance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_seance1ActionPerformed(evt);
            }
        });
        id_seance1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_seance1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(id_seance1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(h1015)
                                .addGap(18, 18, 18)
                                .addComponent(h1715))
                            .addComponent(h1345)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(h830)
                                    .addGap(46, 46, 46)
                                    .addComponent(h1530))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(h12)
                                    .addGap(36, 36, 36)
                                    .addComponent(h1930)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etat_valide)
                        .addGap(18, 18, 18)
                        .addComponent(etat_encoursvalid)
                        .addGap(18, 18, 18)
                        .addComponent(etat_annule))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cours_seance, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(type_cours_seane, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(grp_seance, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(site_seance, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(salle_seane, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(105, 105, 105)
                                                .addComponent(jLabel11)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pro_seance, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salle_capacité, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(Supprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ajouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Editer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(semaine_seance)
                        .addComponent(seance_date, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(236, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(id_seance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(h830)
                    .addComponent(h1530))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(h1015)
                    .addComponent(h1715))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(h12)
                    .addComponent(h1930))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(h1345)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(etat_valide)
                    .addComponent(etat_encoursvalid)
                    .addComponent(etat_annule))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cours_seance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(type_cours_seane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grp_seance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(pro_seance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(salle_seane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(salle_capacité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(site_seance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Supprimer)
                    .addComponent(Ajouter)
                    .addComponent(Editer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(semaine_seance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seance_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Semaine", "Date", "Heure_debut", "Heure_fin", "Etat", "Cours", "Type_cours", "Salle", "Capacité", "Site"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel14.setText("Veuillez rentrer les valeurs que vous souhaitez chercher");

        ValueToResearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueToResearchActionPerformed(evt);
            }
        });
        ValueToResearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValueToResearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ValueToResearch, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValueToResearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValueToResearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueToResearchActionPerformed
        try {
            // TODO add your handling code here:
            jTable1.setModel(new DefaultTableModel(null,new Object[]{"ID","Semaine","Date","Heure_debut","Heure_fin","Etat","Cours","Type_cours","Salle","Capacité","Site"}));
            se.remplissagetableauseance(jTable1, ValueToResearch.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ValueToResearchActionPerformed

    private void ValueToResearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValueToResearchKeyTyped
        // only number:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_ValueToResearchKeyTyped

    public boolean veriftext(){
        if(ValueToResearch.getText().equals("")||semaine_seance.getText().equals("")
                ||cours_seance.getText().equals("")||type_cours_seane.getText().equals("")
                ||seance_date.getDate()==null){
            return false; 
        }else{
            return true;
        }
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int rowIndex = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        ValueToResearch.setText(model.getValueAt(rowIndex,0).toString());
        semaine_seance.setText(model.getValueAt(rowIndex,1).toString());
        type_cours_seane.setText(model.getValueAt(rowIndex,7).toString());
        cours_seance.setText(model.getValueAt(rowIndex,6).toString());
        if (model.getValueAt(rowIndex,3).toString().equals("08:30:00")){
            h830.setSelected(true);
        }else if (model.getValueAt(rowIndex,3).toString().equals("10:15:00")){
            h1015.setSelected(true);
        }else if (model.getValueAt(rowIndex,3).toString().equals("12:00:00")){
            h12.setSelected(true);
        }else if (model.getValueAt(rowIndex,3).toString().equals("13:45:00")){
            h1345.setSelected(true);
        }else if (model.getValueAt(rowIndex,3).toString().equals("15:30:00")){
            h1530.setSelected(true);
        }else if (model.getValueAt(rowIndex,3).toString().equals("17:15:00")){
            h1715.setSelected(true);
        }else if (model.getValueAt(rowIndex,3).toString().equals("19:00:00")){
            h1930.setSelected(true);
        }
        
        if (model.getValueAt(rowIndex,5).toString().equals("0")){
            etat_annule.setSelected(true);
        }else if (model.getValueAt(rowIndex,5).toString().equals("1")){
            etat_encoursvalid.setSelected(true);
        }else if (model.getValueAt(rowIndex,5).toString().equals("2")){
            etat_valide.setSelected(true);
        }
        
        Date dse;
        try {
            dse = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex,2).toString());
            seance_date.setDate(dse);
        } catch (ParseException ex) {
            Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void id_seance1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_seance1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_id_seance1KeyTyped

    private void id_seance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_seance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_seance1ActionPerformed

    private void EditerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditerActionPerformed
        // TODO add your handling code here:
        Connection con;
        try {
            con = SdzConnection.getInstance();
        

            String ID = ValueToResearch.getText();
            String Semaine = semaine_seance.getText();
            String ID_cours = cours_seance.getText();
            String ID_type = type_cours_seane.getText();

            SimpleDateFormat datefor = new SimpleDateFormat("yyyy-MM-dd");
            String seance_d = datefor.format(seance_date.getDate());

            String Etat = "1";
            if (etat_annule.isSelected()){
                Etat = "0";
            }else if (etat_valide.isSelected()){
                Etat = "2";
            }
            String heure_fin;

            String Heure_debut = heure_fin= "";
            if (h830.isSelected()){
                Heure_debut = "08:30:00";
                heure_fin = "10:00:00";
            }else if (h1015.isSelected()){
                Heure_debut = "10:15:00";
                heure_fin = "11:45:00";
            }else if (h12.isSelected()){
                Heure_debut = "12:00:00";
                heure_fin = "13:30:00";
            }else if (h1345.isSelected()){
                Heure_debut = "13:45:00";
                heure_fin = "15:15:00";
            }else if (h1530.isSelected()){
                Heure_debut = "15:30:00";
                heure_fin = "17:00:00";
            }else if (h1715.isSelected()){
                Heure_debut = "17:15:00";
                heure_fin = "18:45:00";
            }else if (h1930.isSelected()){
                Heure_debut = "19:00:00";
                heure_fin = "20:30:00";
            }

            SeanceDAO se = new SeanceDAO(con);
            
                if(veriftext()){
            try {
                se.create('i',ID,Semaine,seance_d,Heure_debut,heure_fin,Etat,ID_cours,ID_type );
                //se.remplissagetableauseance(jTable1, "");
            } catch (SQLException ex) {
                Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
                } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EditerActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SupprimerActionPerformed

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        ajoutse mc;
        
        try {
            mc = new ajoutse();
            mc.setVisible(true);
        mc.pack();
        mc.setLocationRelativeTo(null);
        mc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        /*
        try {
            // ouvrir manageur de cours 
       
        
            // TODO add your handling code here:
            Connection con = SdzConnection.getInstance();

            String ID = ValueToResearch.getText();
            String Semaine = semaine_seance.getText();
            String ID_cours = cours_seance.getText();
            String ID_type = type_cours_seane.getText();

            SimpleDateFormat datefor = new SimpleDateFormat("yyyy-MM-dd");
            String seance_d = datefor.format(seance_date.getDate());

            String Etat = "1";
            if (etat_annule.isSelected()){
                Etat = "0";
            }else if (etat_valide.isSelected()){
                Etat = "2";
            }
            String heure_fin;

            String Heure_debut = heure_fin= "";
            if (h830.isSelected()){
                Heure_debut = "08:30:00";
                heure_fin = "10:00:00";
            }else if (h1015.isSelected()){
                Heure_debut = "10:15:00";
                heure_fin = "11:45:00";
            }else if (h12.isSelected()){
                Heure_debut = "12:00:00";
                heure_fin = "13:30:00";
            }else if (h1345.isSelected()){
                Heure_debut = "13:45:00";
                heure_fin = "15:15:00";
            }else if (h1530.isSelected()){
                Heure_debut = "15:30:00";
                heure_fin = "17:00:00";
            }else if (h1715.isSelected()){
                Heure_debut = "17:15:00";
                heure_fin = "18:45:00";
            }else if (h1930.isSelected()){
                Heure_debut = "19:00:00";
                heure_fin = "20:30:00";
            }

            SeanceDAO se = new SeanceDAO(con);
            try {
                if(veriftext()){
                    se.create('i',ID,Semaine,seance_d,Heure_debut,heure_fin,Etat,ID_cours,ID_type );
                    //se.remplissagetableauseance(jTable1, "");
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_AjouterActionPerformed

    private void etat_annuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etat_annuleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etat_annuleActionPerformed

    private void etat_encoursvalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etat_encoursvalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etat_encoursvalidActionPerformed

    private void etat_valideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etat_valideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etat_valideActionPerformed

    private void h1930ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1930ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h1930ActionPerformed

    private void h1715ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1715ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h1715ActionPerformed

    private void salle_capacitéKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salle_capacitéKeyTyped
        // only number:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_salle_capacitéKeyTyped

    private void salle_capacitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salle_capacitéActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salle_capacitéActionPerformed

    private void site_seanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_site_seanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_site_seanceActionPerformed

    private void salle_seaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salle_seaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salle_seaneActionPerformed

    private void grp_seanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grp_seanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grp_seanceActionPerformed

    private void pro_seanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro_seanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pro_seanceActionPerformed

    private void type_cours_seaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_cours_seaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_cours_seaneActionPerformed

    private void cours_seanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cours_seanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cours_seanceActionPerformed

    private void semaine_seanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semaine_seanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semaine_seanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageCours().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageCours.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Editer;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTextField ValueToResearch;
    private javax.swing.JTextField cours_seance;
    private javax.swing.JRadioButton etat_annule;
    private javax.swing.JRadioButton etat_encoursvalid;
    private javax.swing.JRadioButton etat_valide;
    private javax.swing.JTextField grp_seance;
    private javax.swing.JRadioButton h1015;
    private javax.swing.JRadioButton h12;
    private javax.swing.JRadioButton h1345;
    private javax.swing.JRadioButton h1530;
    private javax.swing.JRadioButton h1715;
    private javax.swing.JRadioButton h1930;
    private javax.swing.JRadioButton h830;
    private javax.swing.JTextField id_seance1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField pro_seance;
    private javax.swing.JTextField salle_capacité;
    private javax.swing.JTextField salle_seane;
    private com.toedter.calendar.JDateChooser seance_date;
    private javax.swing.JTextField semaine_seance;
    private javax.swing.JTextField site_seance;
    private javax.swing.JTextField type_cours_seane;
    // End of variables declaration//GEN-END:variables
}
